
<?php
/**
 * @see Mage_Payment_Block_Info
 */
?>

<?php if ($this->podeConsultar()):?>
<button class="scalable" style="" onclick="setLocation('<? echo $this->getConsultarUrl() ?>');" type="button">
<span>Consultar</span>
</button>
<?php endif;?>

<?php if ($this->podeAutorizar()):?>
<button class="scalable " style="" onclick="setLocation('<? echo $this->getAutorizarUrl() ?>');" type="button">
<span>Autorizar</span>
</button>
<?php endif;?>

<?php if ($this->podeCapturar()):?>
<button class="scalable " style="" onclick="setLocation('<? echo $this->getCapturarUrl() ?>');" type="button">
<span>Capturar (Efetivar cobrança)</span>
</button>
<?php endif;?>

<?php if ($this->podeCancelar()):?>
<button class="scalable " style="" onclick="setLocation('<? echo $this->getCancelarUrl() ?>');" type="button">
<span>Cancelar</span>
</button>
<?php endif;?>
<p/>

<?php echo $this->htmlEscape($this->getMethod()->getTitle()) ?>

<?php if ($_specificInfo = $this->getSpecificInformation()):?>
<table>
<?php foreach ($_specificInfo as $_label => $_value):?>
    <tr>
        <td><?php echo $this->escapeHtml($_label)?>:</td>
        <td><?php echo nl2br(implode($this->getValueAsArray($_value, true), "\n"))?></td>
    </tr>
<?php endforeach; ?>
</table>
<?php endif;?>

<?php echo $this->getChildHtml()?>
